name: SAP BTP Deployment

on:
  # deployment will take place on GitHub PUSH action, whenever there is a push to the 'master' branch (we can change it to any action, Ex: COMMIT)
  push:
    branches:
      - main
      - master
  # for manual deployement
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    # the jobs which will run on this event
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Load NPM dependencies
        run: npm install
      - name: Build Project
        run: npm exec -c "mbt build --mtar build.mtar"
      - name: Deploying Project
        uses: KRAESI-SCHUECO/cf-deploy@main
        with:
          api: ${{ secrets.CF_API_ENDPOINT }}
          user: ${{ secrets.CF_USER }}
          password: ${{ secrets.CF_PASSWORD }}
          space: ${{ secrets.CF_SPACE }}
          org: ${{ secrets.CF_ORG }}
